fix: modified send_email_handler conditional statement
SPARCS-UP-Mindanao/TechTix pull request #276
Opened 2024-10-31 05:40 UTC by jcomrade

2024-10-31 06:22 UTC, ArJSarmiento requested changes
Good idea! Pls implement skipping this way. Thanks

2024-11-01 05:21 UTC, ArJSarmiento requested changes
Please check PR comments. Thanks!

2024-11-01 05:21 UTC, ArJSarmiento commented on backend/usecase/email_usecase.py
> +        if self.__event_email and event.konfhubId and event.konfhubApiKey:
Add a comment why this check exists

2024-11-01 05:21 UTC, ArJSarmiento commented on backend/usecase/email_usecase.py
> +    def __send_email_handler(self, email_in_list: List[EmailIn], event: Event) -> Tuple[HTTPStatus, str]:
Add a docstring for the input and expected output

2024-11-01 05:21 UTC, ArJSarmiento commented on backend/usecase/email_usecase.py
Some `send_batch_email` calls were not refactored. Please check for all instances.

2024-11-01 06:17 UTC, ArJSarmiento requested changes
Please check comments. Thanks!

2024-11-01 06:17 UTC, ArJSarmiento commented on backend/usecase/email_usecase.py
> +        return self.send_batch_email(email_in_list=emails, event=Event)
should be the event variable not the type

2024-11-01 06:17 UTC, ArJSarmiento commented on backend/usecase/email_usecase.py
> +        return self.send_batch_email(email_in_list=emails, event=Event)
should be the event variable not the type. Pls check for the rest of the instances

2024-11-01 06:26 UTC, ArJSarmiento approved these changes
LGTM. Thanks!

2024-11-01 06:26 UTC, merged

2024-11-01 06:36 UTC, jcomrade commented
[konfhubSample.webm](https://github.com/user-attachments/assets/11381168-aecb-4396-b4e9-b09b85d77d2e)

2024-11-01 06:43 UTC, jcomrade commented
[NO_Konfhub_credentials.webm](https://github.com/user-attachments/assets/832ed552-3721-4812-8870-e88cfd5a73c3)

Event Creation and pre-registration without  konfhub id and apikey

Expected output: Email Received for Event Creation